name: frontend_waste_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  simple_circular_progress_bar: 1.0.2
  golden_toolkit: ^0.15.0
  page_view_indicators: ^2.0.0
  camera: ^0.11.0+1
  camera_windows: ^0.2.5
  permission_handler: ^11.3.1
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_map_location_marker: ^8.1.0
  flutter_map_supercluster: ^5.0.0-dev.1
  flutter_map_heatmap: ^0.0.7
  flutter_map_compass: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_map_cancellable_tile_provider: ^2.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Regular.ttf
        - asset: assets/font/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/font/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
